{{- if .Values.hpa.enabled }}
# HPA for the API Deployment
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "iosme-lamar.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "iosme-lamar.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "iosme-lamar.fullname" . }}-api
  minReplicas: {{ .Values.hpa.api.minReplicas }}
  maxReplicas: {{ .Values.hpa.api.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.api.targetCPUUtilizationPercentage }}

---
# HPA for the Worker Deployment
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "iosme-lamar.fullname" . }}-worker
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "iosme-lamar.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "iosme-lamar.fullname" . }}-worker
  minReplicas: {{ .Values.hpa.worker.minReplicas }}
  maxReplicas: {{ .Values.hpa.worker.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.worker.targetCPUUtilizationPercentage }}
{{- end }}
