apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "iosme-lamar.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    compliance.lamar.edu/scope: education-only
    compliance.lamar.edu/regimes: "FERPA,SACSCOC,TitleIX,ADA508,TexasEdCode,AACSB,ABET"
